import "./styles/style.css";
import {Inter} from "next/font/google";

const inter = Inter({subsets:["latin"]});

export const metadata = {
    title: "todo app",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <div style={{ fontFamily: inter }}>
            {children}
        </div>
    );
}